plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/opt/openclaw/mvp-projects/sponsor-connect/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'static build'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]